name: openrouter_app
description: "A Flutter application for chatting with AI models through OpenRouter, providing a user-friendly chat interface and settings customization."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  bloc: ^8.1.4
  equatable: ^2.0.5
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  flutter_markdown: ^0.7.7+1
  flutter_highlight: ^0.7.0
  provider: ^6.1.1
  path_provider: ^2.1.1
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
